language: go
sudo: false

os:
  - linux
  - osx

go:
  - 1.8

install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet ./...
  - go build -v ./...
  - go install -v
  - make coverage
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

after_success:
  - coveralls
